#sserver.port=5001
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:~/datxa/tecstdbs
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.redis.client-name=${REDIS_CLIENT_NAME:}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true

#spring.jackson.mapper.property-naming-strategy=com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy




